identidock:
  build: .
  ports:
   - "5000:5000"
  environment:
    HTTP_PROXY: http://a.vereschaga:1234rewQ@proxy.ctt.com.mps:8080
    HTTPS_PROXY: http://a.vereschaga:1234rewQ@proxy.ctt.com.mps:8080
    ENV: DEV 
#  volumes:
#    - ./app:/app
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0
